export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const SAVE_RECIPE_START = 'SAVE_RECIPE_START';
export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';
export const SAVE_RECIPE_FAIL = 'SAVE_RECIPE_FAIL';
export const SAVE_RECIPE_GET_COUNT_START = 'SAVE_RECIPE_GET_COUNT_START';
export const SAVE_RECIPE_GET_COUNT_SUCCESS = 'SAVE_RECIPE_GET_COUNT_SUCCESS';
export const SAVE_RECIPE_GET_COUNT_FAIL = 'SAVE_RECIPE_GET_COUNT_FAIL';